---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          # General
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

          # Json
          - id: check-json

    - repo: https://github.com/sirosen/texthooks
      rev: 0.4.0
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.2
      hooks:
          - id: prettier
            stages: [commit]

    # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.17.0
      hooks:
          - id: gitlint

    # Markdown

    - repo: https://github.com/tcort/markdown-link-check
      rev: v3.10.3
      hooks:
          - id: markdown-link-check
            args:
                - --config
                - .markdown-link-check.json

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.28.0
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    # Mixed

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: script-must-not-have-extension
          - id: shellcheck
            args: [--external-sources, --format=gcc, --shell=bash]
          - id: shfmt

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.3.1
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.18.3
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.15.0
      hooks:
          - id: gitleaks

    - repo: https://github.com/rhysd/actionlint
      rev: v1.6.21
      hooks:
          - id: actionlint

    - repo: https://github.com/streetsidesoftware/cspell-cli
      rev: v6.12.0
      hooks:
          - id: cspell
