#!/usr/bin/env python
"""Set the last modified date in YAML front matter of edited markdown files.

Credit to Michael Rose (@mmistakes) for the basis of this script.
https://mademistakes.com/notes/adding-last-modified-timestamps-with-git/

Credit to ChatGPT for help converting it to python.
"""

import datetime as dt
import git
import os
import tempfile

# Use Git to get a list of modified Markdown files.
repo = git.Repo(search_parent_directories=True)
diff_index = repo.index.diff('HEAD')
modified_files = [diff.a_path for diff in diff_index if diff.change_type != 'D']
modified_files = [file for file in modified_files if file.endswith('.md')]

# Update the last_modified_at field in each file.
tmpfile = tempfile.mktemp()
last_modified_at = dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%d %H:%M:%S')
for file in modified_files:
    with open(file, 'r') as f:
        lines = f.readlines()
    with open(tmpfile, 'w') as f:
        for line in lines:
            if line.startswith('last_modified_at:'):
                f.write(f'last_modified_at: {last_modified_at}\n')
            else:
                f.write(line)
    os.replace(tmpfile, file)
    repo.git.add(file)
    print(f'Updated modified date for {file}.')
