#!/usr/bin/env bash

set -o errexit                # Exit on error. Append || true if you expect an error.
set -o errtrace               # Exit on error inside any functions or subshells.
set -o noclobber              # Don't allow overwriting files.
set -o nounset                # Don't allow use of undefined vars. Use ${VAR:-} to use an undefined VAR.
set -o pipefail               # Produce a failure return code if any pipeline command errors.
shopt -s failglob             # Cause globs that don't get expanded to cause errors.
shopt -s globstar 2>/dev/null # Match all files and zero or more sub-directories.

# Credit to Michael Rose (@mmistakes) for this script.
# https://mademistakes.com/notes/adding-last-modified-timestamps-with-git/ .

TMPFILE="$(mktemp)"
export TMPFILE

git diff --cached --name-status | \
  grep --ignore-case --extended-regexp "^(A|M).*\.(md)$" | \
  while read -r a b; do
    sed "/---.*/,/---.*/s/^last_modified_at:.*$/last_modified_at: $(date -u "+%Y-%m-%d %H:%M:%S")/" "${b}" >| "${TMPFILE}"
    mv -f "${TMPFILE}" "${b}"
    git add "${b}"
  done
